// Copyright 2024 Team 254. All Rights Reserved.
// Author: pat@patfairbank.com (Patrick Fairbank)
//
// NATS integration for Cheesy Arena.

package websocket

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"log"
	"strings"
	"sync"
	"time"

	"github.com/nats-io/nats-server/v2/server"
	"github.com/nats-io/nats.go"
	"github.com/nats-io/nkeys"
)

var (
	nc           *nats.Conn
	natsMutex    sync.Mutex
	natsServer   string
	ns           *server.Server
	serverKey    nkeys.KeyPair
	operatorKey  nkeys.KeyPair
	accountKey   nkeys.KeyPair
	natsStarted  bool
	natsInternal bool // True if using embedded server

	// Client lifespan management
	clientHeartbeats       = make(map[string]time.Time) // clientId -> last heartbeat time
	clientHeartbeatsMutex  sync.Mutex
	clientCleanupTicker    *time.Ticker
	clientHeartbeatTimeout = 30 * time.Second
)

// StartEmbeddedNATSServer starts an in-process NATS server with WebSocket support.
func StartEmbeddedNATSServer(port int, wsPort int) error {
	var err error
	operatorKey, err = nkeys.CreateOperator()
	if err != nil {
		return err
	}
	accountKey, err = nkeys.CreateAccount()
	if err != nil {
		return err
	}
	serverKey, err = nkeys.CreateServer()
	if err != nil {
		return err
	}

	opts := &server.Options{
		Host: "127.0.0.1",
		Port: port,
		Websocket: server.WebsocketOpts{
			Host:  "0.0.0.0",
			Port:  wsPort,
			NoTLS: true,
		},
		CustomClientAuthentication: &natsAuth{
			operatorKey: operatorKey,
			accountKey:  accountKey,
		},
	}

	ns, err = server.NewServer(opts)
	if err != nil {
		return err
	}

	// Go routine to start the server
	go ns.Start()

	if !ns.ReadyForConnections(10 * time.Second) {
		return nats.ErrNoServers
	}

	natsStarted = true
	log.Printf("Embedded NATS Server started (TCP: 127.0.0.1:%d, WS: 0.0.0.0:%d) with auth", port, wsPort)
	return nil
}

type natsAuth struct {
	operatorKey nkeys.KeyPair
	accountKey  nkeys.KeyPair
}

func (a *natsAuth) Check(c server.ClientAuthentication) bool {
	opts := c.GetOpts()
	token := opts.Token

	// If no token, allow internal or unauthenticated clients full access.
	// In a real environment, this would be restricted, but for the embedded
	// server used by Cheesy Arena itself, we want full permissions.
	if token == "" {
		c.RegisterUser(&server.User{
			Permissions: &server.Permissions{
				Subscribe: &server.SubjectPermission{
					Allow: []string{">"},
				},
				Publish: &server.SubjectPermission{
					Allow: []string{">"},
				},
			},
		})
		return true
	}

	// For clients with a token, register them with basic permissions
	// The token is a simple hex string generated by GenerateNKeyForUser
	// In a real environment, this could be a JWT token with fine-grained permissions
	// For now, we grant full permissions to any authenticated client
	c.RegisterUser(&server.User{
		Permissions: &server.Permissions{
			Publish: &server.SubjectPermission{
				Allow: []string{">"},
			},
			Subscribe: &server.SubjectPermission{
				Allow: []string{">"},
			},
		},
	})

	return true
}

// GenerateNKeyForUser creates a unique token for a user to connect to NATS
// Note: This is actually just a token, not an NKey seed - for simpler authentication
func GenerateNKeyForUser(username string, isAdmin bool) (string, error) {
	if !natsStarted {
		return "", nil // Return empty token if NATS server not started (for unauthenticated access)
	}

	// For simplicity, we'll use a UUID as the authentication token
	// The NATS server will accept this token via the token authentication mechanism
	// In a real implementation, this could be a JWT or actual NKey seed
	token := generateSecureToken()

	return token, nil
}

// generateSecureToken creates a random authentication token
func generateSecureToken() string {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		log.Printf("Warning: Failed to generate secure token: %v", err)
		return ""
	}
	return hex.EncodeToString(b)
}

// InitializeNATS sets up the global NATS connection.
func InitializeNATS(url string) error {
	natsMutex.Lock()
	defer natsMutex.Unlock()

	var err error
	nc, err = nats.Connect(url,
		nats.Name("Cheesy Arena"),
		nats.Timeout(10*time.Second),
		nats.MaxReconnects(-1),
		nats.ReconnectWait(2*time.Second),
		nats.DisconnectErrHandler(func(_ *nats.Conn, err error) {
			log.Printf("NATS disconnected: %v", err)
		}),
		nats.ReconnectHandler(func(nc *nats.Conn) {
			log.Printf("NATS reconnected to %s", nc.ConnectedUrl())
		}),
	)
	if err != nil {
		return err
	}
	natsServer = url
	log.Printf("NATS connected to %s", url)

	// Setup handlers
	setupBootstrapHandler()
	setupCommandHandler()
	setupClientLifecycleManagement()

	return nil
}

// setupClientLifecycleManagement starts the client cleanup routine and sets up disconnect handling.
func setupClientLifecycleManagement() {
	// Start periodic cleanup for inactive clients
	clientCleanupTicker = time.NewTicker(5 * time.Second)
	go func() {
		for range clientCleanupTicker.C {
			cleanupInactiveClients()
		}
	}()

	// Listen for explicit client disconnect signals
	nc.Subscribe("arena.client-disconnect", func(m *nats.Msg) {
		var payload struct {
			ClientId string `json:"clientId"`
		}
		if err := json.Unmarshal(m.Data, &payload); err != nil {
			return
		}
		if payload.ClientId != "" {
			UnregisterClient(payload.ClientId)
		}
	})
}

// recordClientHeartbeat updates the last activity time for a client.
func recordClientHeartbeat(clientId string) {
	if clientId == "" {
		return
	}
	clientHeartbeatsMutex.Lock()
	defer clientHeartbeatsMutex.Unlock()
	clientHeartbeats[clientId] = time.Now()
}

// RecordClientHeartbeat is the exported version of recordClientHeartbeat for external packages.
func RecordClientHeartbeat(clientId string) {
	recordClientHeartbeat(clientId)
}

// cleanupInactiveClients removes clients that haven't sent a heartbeat within the timeout period.
func cleanupInactiveClients() {
	clientHeartbeatsMutex.Lock()
	defer clientHeartbeatsMutex.Unlock()

	now := time.Now()
	for clientId, lastHeartbeat := range clientHeartbeats {
		if now.Sub(lastHeartbeat) > clientHeartbeatTimeout {
			// Remove the client subscription and heartbeat record
			delete(clientHeartbeats, clientId)
			UnregisterClient(clientId)
			log.Printf("Cleaned up inactive client: %s", clientId)
		}
	}
}

// GetNATS returns the global NATS connection.
func GetNATS() *nats.Conn {
	return nc
}

// PublishMessage sends a message to a NATS subject.
func PublishMessage(subject string, messageType string, data any) error {
	if nc == nil {
		return nil // NATS not initialized
	}

	msg := Message{
		Type: messageType,
		Data: data,
	}
	payload, err := json.Marshal(msg)
	if err != nil {
		return err
	}

	return nc.Publish(subject, payload)
}

func setupBootstrapHandler() {
	// Listen for requests on "arena.bootstrap.>"
	// Clients can request initial state for a specific notifier
	nc.Subscribe("arena.bootstrap.>", func(m *nats.Msg) {
		// Subject will be arena.bootstrap.<messageType>
		parts := strings.Split(m.Subject, ".")
		if len(parts) < 3 {
			return
		}
		messageType := parts[2]

		// Find the notifier and get its state
		state := GetNotifierState(messageType)
		if state != nil {
			msg := Message{
				Type: messageType,
				Data: state,
			}
			payload, _ := json.Marshal(msg)
			m.Respond(payload)
		}
	})
}

type CommandHandler func(messageType string, data any, clientId string) bool

var (
	commandHandlers      = make(map[string][]CommandHandler) // path -> handlers
	commandHandlersMutex sync.Mutex
)

// RegisterCommandHandler registers a handler for a specific NATS command path.
// The path should match the one sent from the frontend (e.g., "panels.scoring.red_near").
func RegisterCommandHandler(path string, handler CommandHandler) {
	commandHandlersMutex.Lock()
	defer commandHandlersMutex.Unlock()

	// Normalize path by stripping / and websocket
	normalizedPath := strings.Trim(path, "/")
	normalizedPath = strings.TrimSuffix(normalizedPath, "/websocket")
	normalizedPath = strings.ReplaceAll(normalizedPath, "/", ".")

	commandHandlers[normalizedPath] = append(commandHandlers[normalizedPath], handler)
}

func setupCommandHandler() {
	nc.Subscribe("arena.commands.>", func(m *nats.Msg) {
		handleCommand(m)
	})
}

func handleCommand(m *nats.Msg) {
	// Subject is arena.commands.<path>
	parts := strings.Split(m.Subject, ".")
	if len(parts) < 3 {
		return
	}
	path := strings.Join(parts[2:], ".")

	var payload struct {
		Type     string `json:"type"`
		Data     any    `json:"data"`
		ClientId string `json:"clientId"`
	}
	if err := json.Unmarshal(m.Data, &payload); err != nil {
		return
	}

	// Update client heartbeat to indicate the client is still active
	recordClientHeartbeat(payload.ClientId)

	commandHandlersMutex.Lock()
	handlers, ok := commandHandlers[path]
	if !ok {
		commandHandlersMutex.Unlock()
		return
	}
	// Copy handlers to avoid holding lock during execution
	handlersCopy := make([]CommandHandler, len(handlers))
	copy(handlersCopy, handlers)
	commandHandlersMutex.Unlock()

	for _, handler := range handlersCopy {
		if handler(payload.Type, payload.Data, payload.ClientId) {
			break
		}
	}
}

// CloseNATS closes the NATS connection and cleans up resources.
func CloseNATS() {
	if clientCleanupTicker != nil {
		clientCleanupTicker.Stop()
	}
	if nc != nil {
		nc.Close()
	}
	if ns != nil {
		ns.Shutdown()
	}
}
